-- Preserve the lote movement history so accidental removals can be identified
-- and recovered without relying on the current row alone.

CREATE TABLE IF NOT EXISTS rebanho_lote_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rebanho TEXT NOT NULL,
  id_propriedade TEXT,
  lote_id_anterior TEXT,
  lote_nome_anterior TEXT,
  data_entrada_lote_anterior TIMESTAMPTZ,
  lote_id_novo TEXT,
  lote_nome_novo TEXT,
  data_entrada_lote_nova TIMESTAMPTZ,
  status_rebanho TEXT,
  origem TEXT NOT NULL DEFAULT 'rebanho_update',
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS rebanho_lote_audit_id_rebanho_idx
  ON rebanho_lote_audit (id_rebanho, changed_at DESC);

CREATE OR REPLACE FUNCTION audit_rebanho_lote_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD."loteID" IS DISTINCT FROM NEW."loteID"
    OR OLD."loteNome" IS DISTINCT FROM NEW."loteNome"
    OR OLD."dataEntradaLote" IS DISTINCT FROM NEW."dataEntradaLote" THEN
    INSERT INTO rebanho_lote_audit (
      id_rebanho,
      id_propriedade,
      lote_id_anterior,
      lote_nome_anterior,
      data_entrada_lote_anterior,
      lote_id_novo,
      lote_nome_novo,
      data_entrada_lote_nova,
      status_rebanho
    ) VALUES (
      NEW."idRebanho",
      NEW."idPropriedade",
      OLD."loteID",
      OLD."loteNome",
      OLD."dataEntradaLote",
      NEW."loteID",
      NEW."loteNome",
      NEW."dataEntradaLote",
      NEW."statusRebanho"
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS audit_rebanho_lote_change ON rebanho;

CREATE TRIGGER audit_rebanho_lote_change
  AFTER UPDATE ON rebanho
  FOR EACH ROW
  EXECUTE FUNCTION audit_rebanho_lote_change();
